<?php
        namespace Bcsapi\Traits; 
//This file is generated by running php Artisan BCS:GenerateConstFile 

//***********************************************************************************
//*  DO NOT EDIT THIS FILE - ALL CHANGES MUST BE MADE TO  
//*  https://github.com/tobya/bcsStudents_gitp4/blob/Main/app/Modules/Generator/Services/ConstantClassGeneratorService.php 
//***********************************************************************************
//*  ALL CHANGES TO THIS FILE WILL BE LOST WHEN NEXT GENERATED.
//***********************************************************************************
//*  Generated on:   20th Oct 2025 18:26:26 

 


  trait CourseTypeConstants
  {
        
      const SHORT = 0;
      const COURSE_12_WEEK = 1;
      const AFTERNOON_DEMO = 2;
      const LONG_COURSE = 3;
      const FARM_COURSE = 4;
      const PRIVATE_DEMO = 5;
      const SPECIAL_EVENT = 6;
      const SLOW_FOOD_CLASS = 7;
      const CREDITACCOUNT = 8;
      const NOT_A_COURSE = 9;
      const RESERVED = 10;
      const WELLNESS_COURSE = 11;
      const NIGHT_CLASS = 13;
      const X_CURRICULAR = 14;
      const EXTERNAL = 20;
      const SLOW_FOOD_EVENT = 21;
      const VIRTUAL = 30;
      const V_COOKALONG = 31;
      const STREAM_DEMO = 32;
      const ONLINE_CLASS = 33;
      const FIRESIDE_CHAT = 34;
      const SUBSCRIPTION = 40;
      const VOUCHER_COURSE = 60;
      const WORKEXP = 90;
      const NOTACOURSE = 100;
      const ACCOUNTING_UNIT = 101;
      const PERSON_LIST = 110;
      const GARDEN_TOUR = 120;
      const EVENT = 130;
      const RESOURCES = 140;
      const COTTAGE = 141;
      const KITCHEN_SESSION = 142;
      const ITEMS = 200;
      const CALENDER_ITEM = 201;

    //  Marker for Maximum CourseType. 
      const COURSETYPE_MAXIMUM = 202;

    }
    