<?php

namespace Bcsapi;


use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;

class ApiV4 extends BaseApi
{

        function __construct($APIRootURL, $APIKEY, $AsArray = false){

            parent::__construct($APIRootURL,$APIKEY, $AsArray);

        }

    public function addHeaders(PendingRequest $httpClient)
    {


        return   $httpClient->withToken(config('bcsapi.v4.backoffice.token'))
                            ->acceptJson()
            ->withHeaders(['toby' => Self::class]);
    }

    public function BuildURLString($UrlBlock)
    {
        if (config('bcsapi.v4.backoffice.url') > ''){
            $UrlBlock = '/api' . $UrlBlock;
        }
        return parent::BuildURLString($UrlBlock); // TODO: Change the autogenerated stub
    }
}
