<?php

namespace Bcsapi;


use Illuminate\Http\Client\PendingRequest;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Str;

class ApiV4 extends BaseApi
{

        function __construct($APIRootURL, $APIKEY, $AsArray = false){

            parent::__construct($APIRootURL,$APIKEY, $AsArray);

        }

    /**
     * All Backoffice V4 api calls now require a bearer token, so we add it here.
     * @param PendingRequest $httpClient
     * @return PendingRequest
     */
    public function addHeaders(PendingRequest $httpClient)
    {
        return   $httpClient->withToken(config('bcsapi.v4.backoffice.token','no-token'))
                            ->acceptJson()
                            ->withHeaders(['v4' => Self::class]);
    }

    /**
     * Make modifications to URL.  V4 strings must always start with /api . Add if required.
     * @param $UrlBlock
     * @return string
     * @throws \Exception
     */
    public function BuildURLString($UrlBlock)
    {
        if (!Str::of($UrlBlock)->startsWith('/api')){
            if (Loader::isBackofficeV4()){
                $UrlBlock = '/api' . $UrlBlock;
        }}
        return parent::BuildURLString($UrlBlock); // TODO: Change the autogenerated stub
    }
}
